name: kubernetes-deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4

      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build & Deploy Frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.F_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        env:
          F_IMAGE_NAME: react
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.run_number }}



      - name: Build & Deploy Backend
        uses: docker/build-push-action@v6
        with:
          context: backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.B_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        env:
          B_IMAGE_NAME: node
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.run_number }}



      - name: Setting up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: run echo
        run: echo "Running echo command to verify kubectl setup"

      - name: set contexts In kubectl
        run: kubectl config get-contexts
  
      - name: curr working
        run: pwd

      - name: updating Frontend Deployment image tag
        run: sed -i 's/latest/${{ github.run_number }}/g' kubernetes/frontend-react/react-deploy.yml


      # - name: apply service for Frontend
      #   run: kubectl apply -f kubernetes/frontend-react/react-svc.yml

      - name: apply Frontend Deployment
        run: kubectl apply -f kubernetes/frontend-react/react-deploy.yml


      - name: updating Backend Deployment image tag
        run: sed -i 's/latest/${{ github.run_number }}/g' kubernetes/backend-node/node-deploy.yml

      # - name: apply service for Backend
      #   run: kubectl apply -f kubernetes/backend-node/node-svc.yml

      - name: apply Backend Deployment
        run: kubectl apply -f kubernetes/backend-node/node-deploy.yml 

      # - name: apply mysql secret
      #   run: kubectl apply -f kubernetes/mysql/mysql-secret.yml

      # - name: apply mysql persistent volume
      #   run: kubectl apply -f kubernetes/mysql/mysql-pv.yml 

      # - name: apply mysql persistent volume claim
      #   run: kubectl apply -f kubernetes/mysql/mysql-pvc.yml

      # - name: apply mysql service
      #   run: kubectl apply -f kubernetes/mysql/mysql-heandlessSvc.yml
      
      # - name: apply mysql statefulset
      #   run: kubectl apply -f kubernetes/mysql/mysql-stateful.yml
